# MXNet(Gluon) 入门基础
    MXNet有两种编码风格，Gluon 和 Module, Gluon 更适合入门，这里就从Gluon 开始学起，主要效仿官网相关教程进行渐进式学习。

## 1. 使用ndarry 在mxnet中处理数据

    大家都知道在深度学习过程中，数据时一切的基础，首先我们就先了解下如何构造和存储数据。首先，我们从NDArrays数据结构开始。
    

### 数据构建
首先先导入mxnet 以及ndarray 数据结构，然后尝试随机生成 3行4列 矩阵。

In [1]:
import mxnet as mx
from mxnet import nd
mx.random.seed(1)
x = nd.empty((3,4))
print(x)


[[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.45174521e-42   0.00000000e+00]
 [  0.00000000e+00   4.68374623e-39   0.00000000e+00   6.97960421e-39]]
<NDArray 3x4 @cpu(0)>


此外，还有些初始化数据的方法：
* empty: 从内存中抓取部分数据，进行呈现
* zeros: 全为 0 值数据
* ones: 全为 1 值数据
* random_normal: 范围随机数据，参数为平均值和方差

In [2]:
x = nd.zeros((3,4))
print(x)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>


In [3]:
x = nd.ones((3,4))
print(x)


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>


In [4]:
x = nd.random_normal(3,1,shape=(2,2))
print(x)


[[ 3.03629494  2.50975585]
 [ 2.04982066  3.03751945]]
<NDArray 2x2 @cpu(0)>


使用shape 和 size 方法可以查看相关数据变量的形状和大小

In [5]:
print(x.shape)
print(x.size)

(2, 2)
4


### 数据运算
数据可以进行基础的运算

In [6]:
y = x.T
print('plus + :')
print(x + y)
print('')
print('')
print('multiplication * :')
print(x * y)
print('')
print('')
print('exponentiation * :')
print(nd.exp(x))
print('')
print('')
print('proper matrix-matrix · :')
print(nd.dot(x,y))

plus + :

[[ 6.07258987  4.55957651]
 [ 4.55957651  6.07503891]]
<NDArray 2x2 @cpu(0)>


multiplication * :

[[ 9.21908665  5.14454937]
 [ 5.14454937  9.22652435]]
<NDArray 2x2 @cpu(0)>


exponentiation * :

[[ 20.82793045  12.30192661]
 [  7.7665081   20.85345078]]
<NDArray 2x2 @cpu(0)>


proper matrix-matrix · :

[[ 15.5179615   13.84729195]
 [ 13.84729195  13.42828941]]
<NDArray 2x2 @cpu(0)>


### 值数据更新
在python 的基本操作中，y = x+ y, 其中y的地址是发生变化的，首先会先划分出一块缓存来存放 x + y 的结果，然后将y的指针指向 新的内存地址。可以通过id 方法来证明。 这样不利于大量数据的计算，同时增加了内存泄漏的风险。
但在mxNet可以通过特定操作来避免该问题，直接将数据赋值在原地址上,那就是 [:]，或者 += 。


In [7]:
print('id(y):',id(y))
y= y + x
print('id(y):',id(y))

id(y): 2160913973088
id(y): 2160750517048


In [8]:
print('id(y):', id(y))
y[:] = x + y
print('id(y):', id(y))
y+= x
print('id(y):',id(y))

id(y): 2160750517048
id(y): 2160750517048
id(y): 2160750517048


但其实在这个操作过程中，还是需要一块临时内存来进行数据的存储，然后将该数据存放到变量y指向的地址中去。 但mxnet中提供了另一种方式可以避免时候临时内存，这就是  elemwise_add 和 out 。所有 ndarray数据类型都支持该操作。

In [9]:
nd.elemwise_add(x, y, out=y)


[[ 15.18147469  12.0888443 ]
 [ 10.70903873  15.18759727]]
<NDArray 2x2 @cpu(0)>

### 子元素操作
可以通过索引针对矩阵中的数据进行读取或者赋值

In [10]:
y = nd.zeros((10,10))
(y)
print(y[1,0])
y[1,0] = 99
print(y)
y[0:5,3:6] = 5
print(y)


[ 0.]
<NDArray 1 @cpu(0)>

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 99.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]
<NDArray 10x10 @cpu(0)>

[[  0.   0.   0.   5.   5.   5.   0.   0.   0.   0.]
 [ 99.   0.   0.   5.   5.   5.   0.   0.   0.   0.]
 [  0.   0.   0.   5.   5.   5.   0.   0.   0.   0.]
 [  0.   0.   0.   5.   5.   5.   0.   0.   0.   0.]
 [  0.   0.   0.   5.   5.   5.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0

### 广播
直接可以通过预定义矩阵和向量形状来实现广播操作

In [11]:
x = nd.ones(shape=(3,3))
print('x = ', x)
y = nd.arange(3)
print('y = ', y)
print('x + y = ', x + y)
print('--------------------------------')
y = y.reshape((3,1))
print('y = ', y)
print('x + y = ', x+y)

x =  
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @cpu(0)>
y =  
[ 0.  1.  2.]
<NDArray 3 @cpu(0)>
x + y =  
[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]
<NDArray 3x3 @cpu(0)>
--------------------------------
y =  
[[ 0.]
 [ 1.]
 [ 2.]]
<NDArray 3x1 @cpu(0)>
x + y =  
[[ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]
<NDArray 3x3 @cpu(0)>


### 与NumPy数据结构的相互转换

In [12]:
a = x.asnumpy()
print('type a : ',type(a))
y= nd.array(a)
print('type y : ',type(y))

type a :  <class 'numpy.ndarray'>
type y :  <class 'mxnet.ndarray.ndarray.NDArray'>


### 容器管理
在mxnet中的数据对象可以指定控制存储介质，cpu 或者 gpu，这样有利于发挥服务器硬件性能，缩短计算时间。

In [13]:
z= nd.ones(shape=(3,3),ctx = mx.cpu(0))
z



[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @cpu(0)>