# MXNet(Gluon) 入门基础
    MXNet有两种编码风格，Gluon 和 Module, Gluon 更适合入门，这里就从Gluon 开始学起，主要效仿官网相关教程进行渐进式学习。

## 2.线性代数的应用
    在机器学习以及深度神经网络的应用过程中，线性代数的计算不可或者，这里就将一些常用的线性代数应用在这里进行举例说明。

### 标量
基础的标量能够支持各类基本运算，同时NDArray 也能转化成标量

In [2]:
from mxnet import nd

##########################
# Instantiate two scalars
##########################
x = nd.array([3.0])
y = nd.array([2.0])

##########################
# Add them
##########################
print('x + y = ', x + y)

##########################
# Multiply them
##########################
print('x * y = ', x * y)

##########################
# Divide x by y
##########################
print('x / y = ', x / y)

##########################
# Raise x to the power y.
##########################
print('x ** y = ', nd.power(x,y))

##########################
# convert NDArray to scalar
##########################
print(x.asscalar())

x + y =  
[ 5.]
<NDArray 1 @cpu(0)>
x * y =  
[ 6.]
<NDArray 1 @cpu(0)>
x / y =  
[ 1.5]
<NDArray 1 @cpu(0)>
x ** y =  
[ 9.]
<NDArray 1 @cpu(0)>
3.0


### 向量
    在实际应用过程中，向量结构类似一维举证，并通过下标来直接读写相关子元素。

In [2]:
u =nd.arange(4)
print('u = ', u)
print('u[2]= ',u[2])
u[0] =100
print('u = ', u)

u =  
[ 0.  1.  2.  3.]
<NDArray 4 @cpu(0)>
u[2]=  
[ 2.]
<NDArray 1 @cpu(0)>
u =  
[ 100.    1.    2.    3.]
<NDArray 4 @cpu(0)>


### 长度、维度及形状
    通过来长度，形状方法来确定相关变量的形状以便在操作前进行检查确认。


In [4]:
print('len(u) = ',len(u))
print('u.shape = ',u.shape)

len(u) =  4
u.shape =  (4,)


### 矩阵
一般用大写字母表示矩阵，可以用zeros 或者 ones 进行初始化。同时可以将向量和矩阵进行转化。

In [5]:
A = nd.zeros((5,4))
print('A',A)
x = nd.arange(20)
B = x.reshape((5,4))
print('B',B)

A 
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 5x4 @cpu(0)>
B 
[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
<NDArray 5x4 @cpu(0)>


可以通过索引查看修改对应数据，也可以针对矩阵进行转秩

In [6]:
print('row 2 of B', B[2,:])

row 2 of B 
[  8.   9.  10.  11.]
<NDArray 4 @cpu(0)>


In [7]:
print('column 3 of B', B[:,3])

column 3 of B 
[  3.   7.  11.  15.  19.]
<NDArray 5 @cpu(0)>


In [8]:
print('B.T',B.T)

B.T 
[[  0.   4.   8.  12.  16.]
 [  1.   5.   9.  13.  17.]
 [  2.   6.  10.  14.  18.]
 [  3.   7.  11.  15.  19.]]
<NDArray 4x5 @cpu(0)>


### 张量
    理解为三维数组

In [12]:
X = nd.arange(24).reshape((4, 3, 2))
print('X.shape =', X.shape)
print('X =', X)

X.shape = (4, 3, 2)
X = 
[[[  0.   1.]
  [  2.   3.]
  [  4.   5.]]

 [[  6.   7.]
  [  8.   9.]
  [ 10.  11.]]

 [[ 12.  13.]
  [ 14.  15.]
  [ 16.  17.]]

 [[ 18.  19.]
  [ 20.  21.]
  [ 22.  23.]]]
<NDArray 4x3x2 @cpu(0)>


### 元素计算
    通常情况下，针对矩阵或者数组的操作通过 element-wise 进行操作，确保新建的变量能和原变量有一样的形状，方便计算。

In [13]:
u = nd.array([1, 2, 4, 8])
v = nd.ones_like(u) * 2
w = nd.zeros_like(v)
print('u =', u)
print('v =', v)
print('w =', w)
print('u + v', u + v)
print('u - v', u - v)
print('u * v', u * v)
print('u / v', u / v)

u = 
[ 1.  2.  4.  8.]
<NDArray 4 @cpu(0)>
v = 
[ 2.  2.  2.  2.]
<NDArray 4 @cpu(0)>
w = 
[ 0.  0.  0.  0.]
<NDArray 4 @cpu(0)>
u + v 
[  3.   4.   6.  10.]
<NDArray 4 @cpu(0)>
u - v 
[-1.  0.  2.  6.]
<NDArray 4 @cpu(0)>
u * v 
[  2.   4.   8.  16.]
<NDArray 4 @cpu(0)>
u / v 
[ 0.5  1.   2.   4. ]
<NDArray 4 @cpu(0)>


In [16]:
A = nd.arange(16).reshape((4,4))
B = nd.ones_like(A) * 3
print('B =', B)
print('A + B =', A + B)
print('A * B =', A * B)

B = 
[[ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]]
<NDArray 4x4 @cpu(0)>
A + B = 
[[  3.   4.   5.   6.]
 [  7.   8.   9.  10.]
 [ 11.  12.  13.  14.]
 [ 15.  16.  17.  18.]]
<NDArray 4x4 @cpu(0)>
A * B = 
[[  0.   3.   6.   9.]
 [ 12.  15.  18.  21.]
 [ 24.  27.  30.  33.]
 [ 36.  39.  42.  45.]]
<NDArray 4x4 @cpu(0)>


### 平均值、总和
    常用的基础操作，同样适用于不同的数据类型。

In [18]:
x = nd.arange(10)
print('mean x', nd.mean(x))
print('sum x',nd.sum(x))
A = x.reshape((2,5))
print('mean A', nd.mean(A))
print('sum A', nd.sum(A))

mean x 
[ 4.5]
<NDArray 1 @cpu(0)>
sum x 
[ 45.]
<NDArray 1 @cpu(0)>
mean A 
[ 4.5]
<NDArray 1 @cpu(0)>
sum A 
[ 45.]
<NDArray 1 @cpu(0)>


In [20]:
print(nd.dot(u,v))
print(nd.sum(u*v))


[ 30.]
<NDArray 1 @cpu(0)>

[ 30.]
<NDArray 1 @cpu(0)>


### 矩阵及向量的计算
    了解了点积计算之后，我们就可以开始了解矩阵与向量的的相关计算了。

In [11]:
A = nd.arange(0,20).reshape((4,5))
x = nd.arange(0,5)
print('A:',A)
print('x:',x)
print('Ax:', nd.dot(A,x))

A: 
[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]]
<NDArray 4x5 @cpu(0)>
x: 
[ 0.  1.  2.  3.  4.]
<NDArray 5 @cpu(0)>
Ax: 
[  30.   80.  130.  180.]
<NDArray 4 @cpu(0)>


### 矩阵之间的计算
    矩阵之间也可以进行乘计算

In [12]:
A = nd.arange(1,21).reshape((4,5))
B = nd.arange(50,100).reshape((5,8))
C = nd.dot(A,B)
print('A:',A)
print('B:',B)
print('A·B:',C)

A: 
[[  1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.]
 [ 16.  17.  18.  19.  20.]]
<NDArray 4x5 @cpu(0)>
B: 
[[ 50.  51.  52.  53.  54.  55.  56.  57.]
 [ 58.  59.  60.  61.  62.  63.  64.  65.]
 [ 66.  67.  68.  69.  70.  71.  72.  73.]
 [ 74.  75.  76.  77.  78.  79.  80.  81.]
 [ 82.  83.  84.  85.  86.  87.  88.  89.]]
<NDArray 5x8 @cpu(0)>
A·B: 
[[ 1070.  1085.  1100.  1115.  1130.  1145.  1160.  1175.]
 [ 2720.  2760.  2800.  2840.  2880.  2920.  2960.  3000.]
 [ 4370.  4435.  4500.  4565.  4630.  4695.  4760.  4825.]
 [ 6020.  6110.  6200.  6290.  6380.  6470.  6560.  6650.]]
<NDArray 4x8 @cpu(0)>


### 范数
    二阶范数即为常用的直线距离,直接用norm函数获取

In [25]:
a = nd.arange(-2,2)
print(a)
print(nd.norm(a))
print(nd.abs(a))
print(nd.sum(nd.abs(a)))


[-2. -1.  0.  1.]
<NDArray 4 @cpu(0)>

[ 2.44948983]
<NDArray 1 @cpu(0)>

[ 2.  1.  0.  1.]
<NDArray 4 @cpu(0)>

[ 4.]
<NDArray 1 @cpu(0)>
